name: Docs

on:
  push:
    branches:
      - master

jobs:
  check-changes:
    name: Check changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn build
      - uses: netlify/actions/build@master
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
